<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test9" nsURI="http://jku.bise.at/test9" nsPrefix="test9">
  <eClassifiers xsi:type="ecore:EClass" name="Test9Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test9Root" upperBound="-1"
        eType="#//Test9RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJob" abstract="true" eSuperTypes="#//Test9RootPropertiesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJobRole" eSuperTypes="#//Test9RootJobPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJobLevel" eSuperTypes="#//Test9RootJobPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJobTypeObject" eSuperTypes="#//Test9RootJob">
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" upperBound="-1" eType="#//Test9RootJobPropertiesAbstract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJobPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test9RootJobTypeString" eSuperTypes="#//Test9RootJob">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
