<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test17" nsURI="http://jku.bise.at/test17" nsPrefix="test17">
  <eClassifiers xsi:type="ecore:EClass" name="Test17Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test17Root" upperBound="-1"
        eType="#//Test17RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1" abstract="true" eSuperTypes="#//Test17RootPropertiesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeString" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeInteger" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeNumber" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeBoolean" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeObject" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop1" upperBound="-1"
        eType="#//Test17RootProp1PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1PropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1AdditionalProperties"
      eSuperTypes="#//Test17RootProp1PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeArray" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop1" upperBound="-1"
        eType="#//Test17RootProp1Items" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1Items">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test17RootProp1TypeNull" eSuperTypes="#//Test17RootProp1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop1" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//NullValue"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
