<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test18" nsURI="http://jku.bise.at/test18" nsPrefix="test18">
  <eClassifiers xsi:type="ecore:EClass" name="Test18Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test18Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
