<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jsonMetaschemaMM" nsURI="http://at.jku.bise/jsonMetaschemaMM"
    nsPrefix="jsonMetaschemaMM">
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSchema" eSuperTypes="#//Schema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keywordDefinition" upperBound="-1"
        eType="#//KeywordDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaximumSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WriteOnlySchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueItemsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueItems" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyOfSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyOf" lowerBound="1" eType="#//SchemaArray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringArray">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TitleSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemsAnyOf1" eType="#//Schema"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemsAnyOf2" eType="#//SchemaArray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MinLengthSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minLength" lowerBound="1"
        eType="#//NonNegativeIntegerDefault0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keySchemaPairs" upperBound="-1"
        eType="#//KeySchemaPair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MinItemsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minItems" lowerBound="1"
        eType="#//NonNegativeIntegerDefault0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneOfSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oneOf" lowerBound="1" eType="#//SchemaArray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaArray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxPropertiesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxProperties" lowerBound="1"
        eType="#//NonNegativeInteger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinimumSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxItemsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxItems" lowerBound="1"
        eType="#//NonNegativeInteger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormatSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadOnlySchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyvaluepair" upperBound="-1"
        eType="#//KeyValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAnyOf1" eType="#//SimpleTypes"
        defaultValueLiteral="&quot;array&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typesAnyOf2" eType="#//TypesAnyOf2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalPropertiesSchemaDefinition"
      eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" lowerBound="1" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="const" eType="#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependenciesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//DependenciesAnyOf" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" lowerBound="1"
        eType="#//StringArray" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MinPropertiesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minProperties" lowerBound="1"
        eType="#//NonNegativeIntegerDefault0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternPropertiesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keySchemaPairs" upperBound="-1"
        eType="#//KeySchemaPair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalItemsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalItems" lowerBound="1"
        eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValuePair" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypes">
    <eLiterals name="array" literal="&quot;array&quot;"/>
    <eLiterals name="boolean" value="1" literal="&quot;boolean&quot;"/>
    <eLiterals name="integer" value="2" literal="&quot;integer&quot;"/>
    <eLiterals name="null" value="3" literal="&quot;null&quot;"/>
    <eLiterals name="number" value="4" literal="&quot;number&quot;"/>
    <eLiterals name="object" value="5" literal="&quot;object&quot;"/>
    <eLiterals name="string" value="6" literal="&quot;string&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependenciesAnyOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAnyOf2" eType="#//KeyStringArrayPair"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAnyOf1" eType="#//KeySchemaPair"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExamplesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" lowerBound="1" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllOfSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allOf" lowerBound="1" eType="#//SchemaArray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentEncodingSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentEncoding" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleOfSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleOf" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordDefinition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="not" lowerBound="1" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveMaximumSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMaximum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxLengthSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxLength" lowerBound="1"
        eType="#//NonNegativeInteger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeySchemaPair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentMediaTypeSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentMediaType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveMinimumSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMinimum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertiesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keySchemaPairs" upperBound="-1"
        eType="#//KeySchemaPair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyNamesSchemaDefinition" eSuperTypes="#//KeywordDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyNames" lowerBound="1"
        eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyStringArrayPair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//StringArray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypesAnyOf2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="items" lowerBound="1" upperBound="-1"
        eType="#//SimpleTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanSchema" eSuperTypes="#//Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonNegativeInteger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonNegativeIntegerDefault0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
