<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test39" nsURI="http://jku.bise.at/test39" nsPrefix="test39">
  <eClassifiers xsi:type="ecore:EClass" name="Test39Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test39Root" upperBound="-1"
        eType="#//Test39RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamily" eSuperTypes="#//Test39RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyAllOf0PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PersonalInfo"
      eSuperTypes="#//Test39RootFamilyAllOf0PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalInfo" upperBound="-1"
        eType="#//Test39RootFamilyAllOf0PersonalInfoPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PersonalInfoName"
      eSuperTypes="#//Test39RootFamilyAllOf0PersonalInfoPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PersonalInfoSurname"
      eSuperTypes="#//Test39RootFamilyAllOf0PersonalInfoPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyAllOf1PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfo"
      eSuperTypes="#//Test39RootFamilyAllOf1PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="professionalInfo" upperBound="-1"
        eType="#//Test39RootFamilyAllOf1ProfessionalInfoPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoJob"
      eSuperTypes="#//Test39RootFamilyAllOf1ProfessionalInfoPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoLevel"
      eSuperTypes="#//Test39RootFamilyAllOf1ProfessionalInfoPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoNot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="professionalInfo" upperBound="-1"
        eType="#//Test39RootFamilyAllOf1ProfessionalInfoNotPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoNotAge"
      eSuperTypes="#//Test39RootFamilyAllOf1ProfessionalInfoNotPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" lowerBound="1"
        eType="#//Test39RootFamilyIfAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyIfAnyOf0PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf0Father" eSuperTypes="#//Test39RootFamilyIfAnyOf0PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="father" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyIfAnyOf1PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf1Mother" eSuperTypes="#//Test39RootFamilyIfAnyOf1PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mother" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyThen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyThenPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyThenGrandparent" eSuperTypes="#//Test39RootFamilyThenPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grandparent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test39Root" upperBound="-1"
        eType="#//Test39RootAnyOf0PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf0Email" eSuperTypes="#//Test39RootAnyOf0PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test39Root" upperBound="-1"
        eType="#//Test39RootAnyOf1PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1Telephone" eSuperTypes="#//Test39RootAnyOf1PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1AllOf0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test39Root" upperBound="-1"
        eType="#//Test39RootAnyOf1AllOf0PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1AllOf0Country" eSuperTypes="#//Test39RootAnyOf1AllOf0PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootThen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test39Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootElse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test39Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAdditionalProperties" eSuperTypes="#//Test39RootPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;family&quot;)){return &quot;family&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0AdditionalProperties"
      eSuperTypes="#//Test39RootFamilyAllOf0PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;personalInfo&quot;)){return &quot;personalInfo&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PersonalInfoPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf0PersonalInfoAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyAllOf0PersonalInfoPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;name&quot;)){return &quot;name&quot;;}&#xA;&#xA;if (this.key.equals(&quot;surname&quot;)){return &quot;surname&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1AdditionalProperties"
      eSuperTypes="#//Test39RootFamilyAllOf1PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;professionalInfo&quot;)){return &quot;professionalInfo&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyAllOf1ProfessionalInfoPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;job&quot;)){return &quot;job&quot;;}&#xA;&#xA;if (this.key.equals(&quot;level&quot;)){return &quot;level&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoNotPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyAllOf1ProfessionalInfoNotAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyAllOf1ProfessionalInfoNotPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;age&quot;)){return &quot;age&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeString" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="string"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeInteger" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="integer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeNumber" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="number"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeBoolean" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="boolean"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeObject" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="object"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyIfPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyIfPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeArray" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="array"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//Test39RootFamilyIfItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfTypeNull" eSuperTypes="#//Test39RootFamilyIfAbstract">
    <eAnnotations>
      <details key="ArrayOfTypes" value="null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//NullValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf0PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf0AdditionalProperties"
      eSuperTypes="#//Test39RootFamilyIfAnyOf0PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;father&quot;)){return &quot;father&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf1PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyIfAnyOf1AdditionalProperties"
      eSuperTypes="#//Test39RootFamilyIfAnyOf1PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;mother&quot;)){return &quot;mother&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyThenPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootFamilyThenAdditionalProperties"
      eSuperTypes="#//Test39RootFamilyThenPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;grandparent&quot;)){return &quot;grandparent&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf0PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf0AdditionalProperties"
      eSuperTypes="#//Test39RootAnyOf0PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;email&quot;)){return &quot;email&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1AdditionalProperties"
      eSuperTypes="#//Test39RootAnyOf1PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;telephone&quot;)){return &quot;telephone&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1AllOf0PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test39RootAnyOf1AllOf0AdditionalProperties"
      eSuperTypes="#//Test39RootAnyOf1AllOf0PropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;country&quot;)){return &quot;country&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
