<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test26" nsURI="http://jku.bise.at/test26" nsPrefix="test26">
  <eClassifiers xsi:type="ecore:EClass" name="Test26Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test26Root" lowerBound="1"
        eType="#//Test26RootAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootTypeInteger" eSuperTypes="#//Test26RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test26Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootTypeString" eSuperTypes="#//Test26RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test26Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootTypeArray" eSuperTypes="#//Test26RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test26Root" upperBound="-1"
        eType="#//Test26RootItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootTypeObject" eSuperTypes="#//Test26RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test26Root" upperBound="-1"
        eType="#//Test26RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test26RootAdditionalProperties" eSuperTypes="#//Test26RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
