<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test16" nsURI="http://jku.bise.at/test16" nsPrefix="test16">
  <eClassifiers xsi:type="ecore:EClass" name="Test16Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test16Root" upperBound="-1"
        eType="#//Test16RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test16RootProp1" eSuperTypes="#//Test16RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop1" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//NullValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test16RootPropertiesAbstract" abstract="true"/>
</ecore:EPackage>
