<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test32" nsURI="http://jku.bise.at/test32" nsPrefix="test32">
  <eClassifiers xsi:type="ecore:EClass" name="Test32Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test32Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test32RootAllOf0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test32Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test32RootAnyOf0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test32Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
