<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test4" nsURI="http://jku.bise.at/test4" nsPrefix="test4">
  <eClassifiers xsi:type="ecore:EClass" name="Test4Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test4Root" upperBound="-1"
        eType="#//Test4RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootName" eSuperTypes="#//Test4RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootSurname" eSuperTypes="#//Test4RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootChildrenNames" eSuperTypes="#//Test4RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNames" upperBound="-1"
        eType="#//Test4RootChildrenNamesItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParents" eSuperTypes="#//Test4RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grandParents" upperBound="-1"
        eType="#//Test4RootGrandParentsItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParentsItemsName" eSuperTypes="#//Test4RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParentsItemsSurname" eSuperTypes="#//Test4RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootAdditionalProperties" eSuperTypes="#//Test4RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalProperties" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootChildrenNamesItems">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="items" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParentsItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Test4RootGrandParentsItemsPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParentsItemsAdditionalProperties"
      eSuperTypes="#//Test4RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test4RootGrandParentsItemsPropertiesAbstract"
      abstract="true"/>
</ecore:EPackage>
