<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jsonMM" nsURI="http://at.jku.bise/jsonMM" nsPrefix="jsonMM">
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.getValue().equals(((StringValue)obj).getValue());"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;if (this.getValue().size() != ((ArrayValue) obj).getValue().size())&#xA;&#x9;return false;&#xA;java.util.Collection&lt;Value> copyValues = new java.util.ArrayList&lt;Value>(this.getValue());&#xA;for (Value value : ((ArrayValue) obj).getValue()) {&#xA;&#x9;copyValues.remove(value);&#xA;}&#xA;return copyValues.isEmpty();"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        upperBound="-1" eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.getValue().equals(((NullValue)obj).getValue());"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//NullEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.getValue()==((NumberValue) obj).getValue();"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonDocument">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.getValue().equals(((JsonDocument)obj).getValue());"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;if (this.getKeyvaluepair().size() != ((ObjectValue) obj).getKeyvaluepair().size())&#xA;&#x9;return false;&#xA;java.util.Collection&lt;KeyValuePair> copyKeyvaluepair = new java.util.ArrayList&lt;KeyValuePair>(&#xA;&#x9;&#x9;this.getKeyvaluepair());&#xA;for (KeyValuePair keyValuePair : ((ObjectValue) obj).getKeyvaluepair()) {&#xA;&#x9;copyKeyvaluepair.remove(keyValuePair);&#xA;}&#xA;return copyKeyvaluepair.isEmpty();"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyvaluepair" ordered="false"
        upperBound="-1" eType="#//KeyValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;&#x9;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.isValue()==((BooleanValue)obj).isValue();"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValuePair">
    <eOperations name="equals" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this == obj)&#xA;&#x9;return true;&#xA;if (obj == null)&#xA;&#x9;return false;&#xA;if (getClass() != obj.getClass())&#xA;&#x9;return false;&#xA;return this.getKey().equals(((KeyValuePair)obj).getKey()) &amp;&amp; this.getValue().equals(((KeyValuePair)obj).getValue());"/>
      </eAnnotations>
      <eParameters name="obj" ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NullEnum">
    <eLiterals name="null"/>
  </eClassifiers>
</ecore:EPackage>
