<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test24" nsURI="http://jku.bise.at/test24" nsPrefix="test24">
  <eClassifiers xsi:type="ecore:EClass" name="Test24Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test24Root" lowerBound="1"
        eType="#//Test24RootAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeString" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test24Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeInteger" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test24Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeNumber" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test24Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeBoolean" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test24Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeObject" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test24Root" upperBound="-1"
        eType="#//Test24RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootAdditionalProperties" eSuperTypes="#//Test24RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeArray" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test24Root" upperBound="-1"
        eType="#//Test24RootItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test24RootTypeNull" eSuperTypes="#//Test24RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test24Root" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//NullValue" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
