<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test8" nsURI="http://jku.bise.at/test8" nsPrefix="test8">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyAdditionalPropertiesAdditionalProperties"
      eSuperTypes="#//FamilyAdditionalPropertiesPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootOtherInfo" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherInfo" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootSequentialInfo2Items">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootPatternProperties2" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternProperties2" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test8Root" upperBound="-1"
        eType="#//Test8RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" upperBound="-1"
        eType="#//FamilyPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyAdditionalProperties" eSuperTypes="#//FamilyPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" upperBound="-1"
        eType="#//FamilyAdditionalPropertiesPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyAdditionalPropertiesMembername"
      eSuperTypes="#//FamilyAdditionalPropertiesPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="membername" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyAdditionalPropertiesRelativekind"
      eSuperTypes="#//FamilyAdditionalPropertiesPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativekind" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootName" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootSurname" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootAge" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootAdult" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adult" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootScore" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootJob" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" upperBound="-1" eType="#//Test8RootJobPropertiesAbstract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootJobRole" eSuperTypes="#//Test8RootJobPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootJobLevel" eSuperTypes="#//Test8RootJobPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pippo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pippo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootCar" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="car" upperBound="-1" eType="#//Test8RootCarPropertiesAbstract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootCarLicencePlate" eSuperTypes="#//Test8RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licencePlate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootCarYear" eSuperTypes="#//Test8RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootChildrenNames" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNames" upperBound="-1"
        eType="#//Test8RootChildrenNamesItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootChildrenNamesItems">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="items" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootSequentialInfo" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequentialInfo" upperBound="-1"
        eType="#//Test8RootSequentialInfoItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootSequentialInfo2" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequentialInfo2" upperBound="-1"
        eType="#//Test8RootSequentialInfo2Items" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParents" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grandParents" upperBound="-1"
        eType="#//Test8RootGrandParentsItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParentsItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Test8RootGrandParentsItemsPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParentsItemsName" eSuperTypes="#//Test8RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParentsItemsSurname" eSuperTypes="#//Test8RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootMyFamily" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myFamily" lowerBound="1"
        eType="#//Family" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootWives" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wives" upperBound="-1"
        eType="#//Test8RootWivesPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootWivesAdditionalProperties"
      eSuperTypes="#//Test8RootWivesPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="#//Family" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootExtraFamilies" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraFamilies" upperBound="-1"
        eType="#//Test8RootExtraFamiliesItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootExtraFamiliesItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="#//Family"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootAdditionalProperties" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalProperties" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootPatternProperties0" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternProperties0" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootPatternProperties1" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternProperties1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootPatternProperties3" eSuperTypes="#//Test8RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternProperties3" lowerBound="1"
        eType="#//Family" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyAdditionalPropertiesPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootJobPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootCarPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootCarAdditionalProperties" eSuperTypes="#//Test8RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootSequentialInfoItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParentsItemsPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootGrandParentsItemsAdditionalProperties"
      eSuperTypes="#//Test8RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test8RootWivesPropertiesAbstract" abstract="true"/>
</ecore:EPackage>
