<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test36" nsURI="http://jku.bise.at/test36" nsPrefix="test36">
  <eClassifiers xsi:type="ecore:EClass" name="Test36Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test36Root" upperBound="-1"
        eType="#//Test36RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootIf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test36Root" upperBound="-1"
        eType="#//Test36RootIfPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootIfName" eSuperTypes="#//Test36RootIfPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootThen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test36Root" upperBound="-1"
        eType="#//Test36RootThenPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootThenSurname" eSuperTypes="#//Test36RootThenPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootElse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test36Root" upperBound="-1"
        eType="#//Test36RootElsePropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootElseFullname" eSuperTypes="#//Test36RootElsePropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootAdditionalProperties" eSuperTypes="#//Test36RootPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootIfPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootIfAdditionalProperties" eSuperTypes="#//Test36RootIfPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;name&quot;)){return &quot;name&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootThenPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootThenAdditionalProperties"
      eSuperTypes="#//Test36RootThenPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;surname&quot;)){return &quot;surname&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootElsePropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test36RootElseAdditionalProperties"
      eSuperTypes="#//Test36RootElsePropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;fullname&quot;)){return &quot;fullname&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
