<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test25" nsURI="http://jku.bise.at/test25" nsPrefix="test25">
  <eClassifiers xsi:type="ecore:EClass" name="Test25Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test25Root" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
