<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test23" nsURI="http://jku.bise.at/test23" nsPrefix="test23">
  <eClassifiers xsi:type="ecore:EClass" name="Test23Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test23Root" lowerBound="1"
        eType="#//Test23RootAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test23RootAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test23RootTypeInteger" eSuperTypes="#//Test23RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test23Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test23RootTypeString" eSuperTypes="#//Test23RootAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test23Root" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
