/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.ide;

import at.jku.bise.JsonSchemaDslRuntimeModule;
import at.jku.bise.JsonSchemaDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonSchemaDslIdeSetup extends JsonSchemaDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonSchemaDslRuntimeModule(), new JsonSchemaDslIdeModule()));
	}
	
}
