/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonSchemaDslUiModule extends AbstractJsonSchemaDslUiModule {

	public JsonSchemaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
