<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test76" nsURI="http://jku.bise.at/test76" nsPrefix="test76">
  <eClassifiers xsi:type="ecore:EClass" name="Test76Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test76Root" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
