/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJsonSchemaDslScopeProvider extends DelegatingScopeProvider {
}
