/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.ui.tests;

import com.google.inject.Injector;
import jsonschemadsl.ui.internal.JsonschemadslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class JsonSchemaDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JsonschemadslActivator.getInstance().getInjector("at.jku.bise.JsonSchemaDsl");
	}

}
