/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.parser.antlr;

import at.jku.bise.parser.antlr.internal.InternalJsonSchemaDslParser;
import at.jku.bise.services.JsonSchemaDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JsonSchemaDslParser extends AbstractAntlrParser {

	@Inject
	private JsonSchemaDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonSchemaDslParser createParser(XtextTokenStream stream) {
		return new InternalJsonSchemaDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JsonSchema";
	}

	public JsonSchemaDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonSchemaDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
