/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JsonSchemaDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/jku/bise/parser/antlr/internal/InternalJsonSchemaDsl.tokens");
	}
}
