<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test6" nsURI="http://jku.bise.at/test6" nsPrefix="test6">
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootSequentialInfo2Items">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass /jsonmetaschemaMM/model/jsonMetaschemaMM.ecore#//JsonSchema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test6Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test6Root" upperBound="-1"
        eType="#//Test6RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootSequentialInfo" eSuperTypes="#//Test6RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequentialInfo" upperBound="-1"
        eType="#//Test6RootSequentialInfoItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootSequentialInfo2" eSuperTypes="#//Test6RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequentialInfo2" upperBound="-1"
        eType="#//Test6RootSequentialInfo2Items" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootAdditionalProperties" eSuperTypes="#//Test6RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalProperties" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test6RootSequentialInfoItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass /jsonmetaschemaMM/model/jsonMetaschemaMM.ecore#//JsonSchema"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
