<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test3" nsURI="http://jku.bise.at/test3" nsPrefix="test3">
  <eClassifiers xsi:type="ecore:EClass" name="Test3Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test3Root" upperBound="-1"
        eType="#//Test3RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootCar" eSuperTypes="#//Test3RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="car" upperBound="-1" eType="#//Test3RootCarPropertiesAbstract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootCarLicencePlate" eSuperTypes="#//Test3RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licencePlate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootCarYear" eSuperTypes="#//Test3RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootCarPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test3RootCarAdditionalProperties" eSuperTypes="#//Test3RootCarPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass /jsonmetaschemaMM/model/jsonMetaschemaMM.ecore#//JsonDocument"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
