<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test15" nsURI="http://jku.bise.at/test15" nsPrefix="test15">
  <eClassifiers xsi:type="ecore:EClass" name="Test15Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test15Root" upperBound="-1"
        eType="#//Test15RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootProp1" abstract="true" eSuperTypes="#//Test15RootPropertiesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootProp2" eSuperTypes="#//Test15RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop2" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootProp3" eSuperTypes="#//Test15RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop3" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootProp1TypeInteger" eSuperTypes="#//Test15RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test15RootProp1TypeString" eSuperTypes="#//Test15RootProp1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prop1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
