<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test33" nsURI="http://jku.bise.at/test33" nsPrefix="test33">
  <eClassifiers xsi:type="ecore:EClass" name="Test33Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test33Root" upperBound="-1"
        eType="#//Test33RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test33Root" upperBound="-1"
        eType="#//Test33RootOneOf0PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf0Email" eSuperTypes="#//Test33RootOneOf0PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test33Root" upperBound="-1"
        eType="#//Test33RootOneOf1PropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf1Telephone" eSuperTypes="#//Test33RootOneOf1PropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootNot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test33Root" upperBound="-1"
        eType="#//Test33RootNotPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootNotName" eSuperTypes="#//Test33RootNotPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootAdditionalProperties" eSuperTypes="#//Test33RootPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf0PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootOneOf1PropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test33RootNotPropertiesAbstract" abstract="true"/>
</ecore:EPackage>
