/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonSchemaDslRuntimeModule extends AbstractJsonSchemaDslRuntimeModule {
}
