<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test30" nsURI="http://jku.bise.at/test30" nsPrefix="test30">
  <eClassifiers xsi:type="ecore:EClass" name="Test30Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test30Root" upperBound="-1"
        eType="#//Test30RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootArray" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" upperBound="-1"
        eType="#//Test30RootArrayItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootInteger" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootNumber" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootObject" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" upperBound="-1"
        eType="#//Test30RootObjectPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootNull" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="null" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//NullValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootString" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootBoolean" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolean" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootAdditionalProperties" eSuperTypes="#//Test30RootPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (this.key.equals(&quot;array&quot;)){return &quot;array&quot;;}&#xA;&#xA;if (this.key.equals(&quot;integer&quot;)){return &quot;integer&quot;;}&#xA;&#xA;if (this.key.equals(&quot;number&quot;)){return &quot;number&quot;;}&#xA;&#xA;if (this.key.equals(&quot;object&quot;)){return &quot;object&quot;;}&#xA;&#xA;if (this.key.equals(&quot;null&quot;)){return &quot;null&quot;;}&#xA;&#xA;if (this.key.equals(&quot;string&quot;)){return &quot;string&quot;;}&#xA;&#xA;if (this.key.equals(&quot;boolean&quot;)){return &quot;boolean&quot;;}&#xA;&#xA;return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootArrayItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootObjectPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test30RootObjectAdditionalProperties"
      eSuperTypes="#//Test30RootObjectPropertiesAbstract">
    <eAnnotations>
      <details key="AdditionalProperties" value="true"/>
    </eAnnotations>
    <eOperations name="validateKeyOnDefinedPatternProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="validateKeyOnDefinedProperties" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;&#xA;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
