<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test10" nsURI="http://jku.bise.at/test10" nsPrefix="test10">
  <eClassifiers xsi:type="ecore:EClass" name="Test10Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test10Root" upperBound="-1"
        eType="#//Test10RootPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootName" eSuperTypes="#//Test10RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootSurname" eSuperTypes="#//Test10RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootChildrenNames" abstract="true"
      eSuperTypes="#//Test10RootPropertiesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootChildrenNamesItems">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="items" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParents" abstract="true"
      eSuperTypes="#//Test10RootPropertiesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Test10RootGrandParentsItemsPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsItemsName" eSuperTypes="#//Test10RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsItemsSurname"
      eSuperTypes="#//Test10RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootAdditionalProperties" abstract="true"
      eSuperTypes="#//Test10RootPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootPropertiesAbstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootChildrenNamesTypeArray" eSuperTypes="#//Test10RootChildrenNames">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenNames" upperBound="-1"
        eType="#//Test10RootChildrenNamesItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootChildrenNamesTypeString" eSuperTypes="#//Test10RootChildrenNames">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="childrenNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsTypeArray" eSuperTypes="#//Test10RootGrandParents">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grandParents" upperBound="-1"
        eType="#//Test10RootGrandParentsItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsTypeString" eSuperTypes="#//Test10RootGrandParents">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grandParents" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsItemsPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootGrandParentsItemsAdditionalProperties"
      eSuperTypes="#//Test10RootGrandParentsItemsPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootAdditionalPropertiesTypeString"
      eSuperTypes="#//Test10RootAdditionalProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalProperties" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootAdditionalPropertiesTypeObject"
      eSuperTypes="#//Test10RootAdditionalProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" upperBound="-1"
        eType="#//Test10RootAdditionalPropertiesPropertiesAbstract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootAdditionalPropertiesPropertiesAbstract"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test10RootAdditionalPropertiesAdditionalProperties"
      eSuperTypes="#//Test10RootAdditionalPropertiesPropertiesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" lowerBound="1"
        eType="ecore:EClass http://at.jku.bise/jsonMetaschemaMM#//JsonDocument" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
