/*
 * generated by Xtext 2.23.0
 */
package at.jku.bise.ui;

import com.google.inject.Injector;
import jsonschemadsl.ui.internal.JsonschemadslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JsonSchemaDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JsonschemadslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JsonschemadslActivator activator = JsonschemadslActivator.getInstance();
		return activator != null ? activator.getInjector(JsonschemadslActivator.AT_JKU_BISE_JSONSCHEMADSL) : null;
	}

}
